[package]
build = 'build.rs'
edition = '2018'
name = 'ton_block_json'
version = '0.7.22'

[dependencies]
base64 = '0.13'
failure = '0.1.8'
hex = '0.4.0'
num = '0.4'
num-traits = '0.2'
serde = '1.0.105'
serde_derive = '1.0.105'
serde_json = { features = [ 'preserve_order' ], version = '^1.0' }
ton_api = { git ='https://github.com/tonlabs/ton-labs-tl.git', package = 'ton_api' }
ton_block = { git ='https://github.com/tonlabs/ton-labs-block.git' }
ton_types = { git ='https://github.com/tonlabs/ton-labs-types.git' }

[patch.'https://github.com/tonlabs/ton-labs-block.git']
ton_block = { git = 'ssh://git@github.com:22/tonlabs/ton-block.git', branch = "feature-use-bls-key" }

[patch.'ssh://git@github.com/tonlabs/ton-block.git']
ton_block = { git = 'ssh://git@github.com:22/tonlabs/ton-block.git', branch = "feature-use-bls-key" }
