[package]
build = 'build.rs'
edition = '2018'
name = 'ton_block_json'
version = '0.7.5'

[dependencies]
base64 = '0.11.0'
failure = '0.1.8'
hex = '0.4.0'
num = '0.4'
num-traits = '0.2'
serde = '1.0.105'
serde_derive = '1.0.105'
serde_json = { features = [ 'preserve_order' ], version = '^1.0' }
ton_block = { git = 'https://github.com/tonlabs/ton-labs-block', tag = '1.7.39' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types', tag = '1.10.12' }

[dev-dependencies]
