[package]
build = 'build.rs'
edition = '2018'
name = 'ton_block_json'
version = '0.7.14'

[dependencies]
base64 = '0.13'
failure = '0.1.8'
hex = '0.4.0'
num = '0.4'
num-traits = '0.2'
serde = '1.0.105'
serde_derive = '1.0.105'
serde_json = { features = [ 'preserve_order' ], version = '^1.0' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl', package = 'ton_api', tag = '0.2.126' }
ton_block = { git = 'https://github.com/tonlabs/ton-labs-block', tag = '1.7.47' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types', tag = '1.11.0' }

[dev-dependencies]
